config/routes.rb
Rails.application.routes.draw do
  resources :walks

end

app/models/walk.rb
class Walk < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
  before_action :set_walk, only: [:show, :edit, :update, :destroy]

  # GET /walks
  # GET /walks.json
  def index
    @walks = Walk.all
  end

  # GET /walks/1
  # GET /walks/1.json
  def show
  end

  # GET /walks/new
  def new
    @walk = Walk.new
  end

  # GET /walks/1/edit
  def edit
  end

  # POST /walks
  # POST /walks.json
  def create
    @walk = Walk.new(walk_params)

    respond_to do |format|
      if @walk.save
        format.html { redirect_to @walk, notice: 'Walk was successfully created.' }
        format.json { render :show, status: :created, location: @walk }
      else
        format.html { render :new }
        format.json { render json: @walk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walks/1
  # PATCH/PUT /walks/1.json
  def update
    respond_to do |format|
      if @walk.update(walk_params)
        format.html { redirect_to @walk, notice: 'Walk was successfully updated.' }
        format.json { render :show, status: :ok, location: @walk }
      else
        format.html { render :edit }
        format.json { render json: @walk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walks/1
  # DELETE /walks/1.json
  def destroy
    @walk.destroy
    respond_to do |format|
      format.html { redirect_to walks_url, notice: 'Walk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_walk
      @walk = Walk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def walk_params
      params.require(:walk).permit(:walker_name, :time_out, :time_in)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/walks_helper.rb
module WalksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoSignOutSheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">




</head>
<body>

<%= yield %>

</body>
</html>

app/views/walks/_form.html.erb
<%= form_for(@walk)  do |f| %>
  <% if @walk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@walk.errors.count, "error") %> prohibited this walk from being saved:</h2>

      <ul>
      <% @walk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :walker_name %><br>
    <%= f.text_field :walker_name %>
  </div>
  <div class="field">
    <%= f.label :time_out %><br>
    <%= f.datetime_select :time_out %>
  </div>
  <div class="field">
    <%= f.label :time_in %><br>
    <%= f.datetime_select :time_in %>
  </div>
  <div class="actions">
    <%= f.submit "submit", class: "btn btn-danger" %>
  </div>
<% end %>

app/views/walks/edit.html.erb
<h1>Editing Walk</h1>

<%= render 'form' %>

<%= link_to 'Show', @walk %> |
<%= link_to 'Back', walks_path %>

app/views/walks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Walks</h1>

<table>
  <thead>
    <tr>
      <th>Walker name</th>
      <th>Time out</th>
      <th>Time in</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @walks.each do |walk| %>
      <tr>
        <td><%= walk.walker_name %></td>
        <td><%= walk.time_out %></td>
        <td><%= walk.time_in %></td>
        <td><%= link_to 'Show', walk %></td>
        <td><%= link_to 'Edit', edit_walk_path(walk) %></td>
        <td><%= link_to 'Destroy', walk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Walk', new_walk_path %>

app/views/walks/new.html.erb
<h1>New Walk</h1>

<%= render 'form' %>

<%= link_to 'Back', walks_path %>

app/views/walks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Walker name:</strong>
  <%= @walk.walker_name %>
</p>

<p>
  <strong>Time out:</strong>
  <%= @walk.time_out %>
</p>

<p>
  <strong>Time in:</strong>
  <%= @walk.time_in %>
</p>

<%= link_to 'Edit', edit_walk_path(@walk) %> |
<%= link_to 'Back', walks_path %>